// author: lohitha bhethalam 
const DataStore = require('nedb')
const LOG = require('../utils/logger.js')
const products=require('../data/product.json')
const customers = require('../data/customers.json')
const orders=require('../data/orders.json')
const orderlineitem=require('../data/orderlineitem.json')
module.exports = (app) => {
    LOG.info('START seeder.')
    const db = {}
    db.customers = new DataStore()
    db.customers.loadDatabase()
    db.customers.insert(customers)
    app.locals.customers = db.customers.find(customers)
    LOG.debug(`${app.locals.customers.query.length} customer seeded`)
    db.products = new DataStore()
    db.products.loadDatabase()
    db.products.insert(products)
    app.locals.products = db.products.find(products)
    LOG.debug(`${app.locals.products.query.length} product seeded`)
    db.orders = new DataStore()
    db.orders.loadDatabase()
    db.orders.insert(orders)
    app.locals.orders = db.orders.find(orders)
    LOG.debug(`${app.locals.orders.query.length} order seeded`)
    db.orderLineItems = new DataStore()
    db.orderLineItems.loadDatabase()
    db.orderLineItems.insert(orderlineitem)
    app.locals.orderLineItems = db.orderLineItems.find(orderlineitem)
    LOG.debug(`${app.locals.orderLineItems.query.length} orderlineitem seeded`)
  
    LOG.info('END Seeder.Sample data read and verified.')
}
